// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

namespace TEMS.Business.Entities.Models
{
    public partial class Events
    {
        public Events()
        {
            TalksDetails = new HashSet<TalksDetails>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public DateTime StartDate { get; set; }
        public DateTime EndDate { get; set; }
        public bool IsCompleted { get; set; }
        public int VenueId { get; set; }

        public virtual Venues Venue { get; set; }
        public virtual ICollection<TalksDetails> TalksDetails { get; set; }
    }
}