// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

namespace TEMS.Business.Entities.Models
{
    public partial class Speakers
    {
        public Speakers()
        {
            TalksDetails = new HashSet<TalksDetails>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Organisation { get; set; }
        public string LinkedinUrl { get; set; }
        public string TwitterHandle { get; set; }

        public virtual ICollection<TalksDetails> TalksDetails { get; set; }
    }
}