// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

namespace TEMS.Business.Entities.Models
{
    public partial class TalksDetails
    {
        public int Id { get; set; }
        public int EventId { get; set; }
        public string Title { get; set; }
        public int SpeakerId { get; set; }
        public DateTime StartTime { get; set; }
        public DateTime EndTime { get; set; }
        public string Tags { get; set; }

        public virtual Events Event { get; set; }
        public virtual Speakers Speaker { get; set; }
    }
}