// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

namespace TEMS.Business.Entities.Models
{
    public partial class Venues
    {
        public Venues()
        {
            Events = new HashSet<Events>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public string City { get; set; }
        public string Address { get; set; }
        public string Website { get; set; }
        public string ContactNo { get; set; }

        public virtual ICollection<Events> Events { get; set; }
    }
}